FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json tsconfig.json ./

COPY backend/ ./backend/
COPY shared/ ./shared/

RUN npm install

WORKDIR /app/backend

CMD ["npm", "run", "start:dev"]
