name: Continuous Deployment

on:
    push:
        branches:
            - production
    workflow_dispatch:

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            issues: write
        outputs:
            release_created: ${{ steps.release.outputs.release_created }}
            tag_name: ${{ steps.release.outputs.tag_name }}
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Release
              id: release
              uses: googleapis/release-please-action@v4
              with:
                  manifest-file: .release-please-manifest.json
                  config-file: release-please-config.json
                  token: ${{ secrets.PAT_TOKEN }}

    deploy:
        needs: release
        if: ${{ needs.release.outputs.release_created || github.event_name == 'workflow_dispatch' }}

        name: Build & Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build & Push to ECR
              env:
                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  ECR_REPOSITORY: typing-race/repo
                  IMAGE_TAG: ${{ github.sha }}
              run: |
                  docker build -f ./backend/DockerFile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
                  docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
                  docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
                  docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

            - name: Deploy to Elastic Beanstalk
              uses: einaregilsson/beanstalk-deploy@v22
              with:
                  aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  application_name: typing-race
                  environment_name: typing-race-prod
                  region: ${{ secrets.AWS_REGION }}
                  image_tag: ${{ github.sha }}
                  version_label: ${{ needs.release.outputs.tag_name }}
