name: Continuous Deployment

on:
    push:
        branches:
            - production
    workflow_dispatch:

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            issues: write
        outputs:
            release_created: ${{ steps.release.outputs.release_created }}
            tag_name: ${{ steps.release.outputs.tag_name }}
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4

            - name: Release
              id: release
              uses: googleapis/release-please-action@v4
              with:
                  manifest-file: .release-please-manifest.json
                  config-file: release-please-config.json
                  token: ${{ secrets.PAT_TOKEN }}
